backend:
  name: github
  repo: SmexiCH/WikiSt-ria
  branch: main
  auth_type: oauth
  client_id: "Ov23liVfBMHTp2tlgAuN"
  auth_scope: "repo"
  client_secret: "98ddd38aa88d2271a337ad1a226749a445da2c1c"

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "content"
    label: "Content"
    folder: "content"
    create: true
    format: "frontmatter"
    extension: "md"
    nested:
      depth: 100
      summary: "{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
